GreenHB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('housingbook.urls')),
    path('admin/', admin.site.urls),
]

housingbook/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('my_apartment/', views.my_apartment, name='my_apartment'),
    path('detail/<int:apartment_id>/', views.detail, name='detail'),
    path('operatoroverview/', views.op_overview, name='op_overview'),
    
    path('privacy/', TemplateView.as_view(template_name='housingbook/privacy.html'), name='privacy'),

    url(r'^$', views.home, name='home'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
]

housingbook/models.py
from django.db import models
from django.contrib.auth.models import User

class Owner(models.Model):
    name = models.CharField(max_length=200, blank=True)
    first_name = models.CharField(max_length=200, blank=True)
    society = models.CharField(max_length=200, blank=True)
    
    def __str__(self):
        if not self.society:
            return self.first_name + " " + self.name;
        else:
            return self.society;

class Tenant(models.Model):
    name = models.CharField(max_length=200)
    first_name = models.CharField(max_length=200)

    def __str__(self):
        return self.first_name + " " + self.name;

class Apartment(models.Model):
    code = models.CharField(max_length=200)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return "Apartment " + self.code

class Consumption(models.Model):
    apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
    reading_date = models.DateTimeField('Reading Date')
    reading_value = models.IntegerField(default=0)
    
    def __str__(self):
        return str(self.apartment) + ": " + str(self.reading_value) + " on " + self.reading_date.strftime("%d.%m.%Y") #%H %M %S

housingbook/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

housingbook/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from .models import Apartment, Consumption

@login_required
def index(request):
    return render(request, 'housingbook/index.html')

@login_required
def my_apartment(request):         
    #get the apartment just for the current user
    apartments = Apartment.objects.filter( user=request.user )
    
    if len(apartments) == 0: #use len instead of count to save one database access. count would have generated a SELECT COUNT(*) query, which is extra load on the db.
    #TODO: The db might be faster to get the number of rows. Do some profiling
        # handle error and ask user to ask operator to link them
        return render(request, 'housingbook/index.html')
        
    #there will only be one apartment.
    apartment = apartments.first()
        
    latest_consumption_list = Consumption.objects.filter( apartment_id=apartment.id ).order_by('-reading_date')#[:5]

    context = {
        'apartment': apartment,
        'latest_consumption_list': latest_consumption_list,
    }
    
    return render(request, 'housingbook/detail.html', context)
  
@staff_member_required  
def detail(request, apartment_id):
    apartment = get_object_or_404(Apartment, pk=apartment_id)
    
    context = {
        'apartment': apartment,
    }
    
    return render(request, 'housingbook/detail.html', context)
    
@staff_member_required
def op_overview(request):
    apartments = Apartment.objects.all()
    
    context = {
        'apartment_list': apartments,
    }
    return render(request, 'housingbook/op_overview.html', context)

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.')
    else:
        return HttpResponse('Activation link is invalid!')

housingbook/templates/housingbook/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

housingbook/templates/housingbook/apt_list.html
{% extends 'housingbook/base.html' %}
{% block title %}Apartments{% endblock %}

{% block content %}

    These are the apartments you are entitled to access:

    {% if apt_list %}
        <ul>
        {% for apt in apt_list %}
            <li><a href="{% url 'detail' apt.id %}">Apartment {{ apt.code }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No apartments available.</p>
    {% endif %}
{% endblock %}

housingbook/templates/housingbook/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'housingbook/style.css' %}">
    <title>{% block title %}GreenHB{% endblock %}</title>
</head>

<body>
    <div id="header">
        <a href="{% url 'index' %}"><img src="{% static 'housingbook/images/GREENHB_logo_big.png' %}" /></a>
    </div>
    <div id="navigation">
        {% block navigation %}
        <ul>
            <li><a href="{% url 'index' %}">Start</a></li>
            <li><a href="{% url 'my_apartment' %}">My apartment</a></li>
            {% if user.is_staff %}
                <li><a href="{% url 'op_overview' %}">Operator overview</a></li>
                <li><a href="/admin">Administration</a></li>
            {% endif %}
        </ul>
        <li>
            {% if user.is_authenticated %}
                <a href="/accounts/logout/">Logout</a>
            {% else %}
                <a href="/accounts/login/">Login</a>
            {% endif %}
         </li>
        {% endblock %}
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <div id="footer">
        <a href="{% url 'privacy' %}">Privacy</a>
    </div>
</body>
</html>

housingbook/templates/housingbook/detail.html
{% extends 'housingbook/base.html' %}
{% block title %}Apartment {{ apartment.code }}{% endblock %}

{% block content %}
    Apartment: {{ apartment.code }}

    {% if latest_consumption_list %}
        <ul>
        {% for consumption in apartment.consumption_set.all %}
            <li>{{ consumption.reading_date }}: {{ consumption.reading_value }}</li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No consumption data available.</p>
    {% endif %}
{% endblock %}

housingbook/templates/housingbook/index.html
{% extends 'housingbook/base.html' %}

{% block content %}
    Welcome to GreenHB!
{% endblock %}

housingbook/templates/housingbook/op_overview.html
{% extends 'housingbook/base.html' %}
{% block title %}Operator overview{% endblock %}

{% block content %}
    The following apartments and consumptions are known to GreenHB:

    {% if apartment_list %}
        <ul>
        {% for apartment in apartment_list %}
            <li>Apartment: {{ apartment.code }}</li>
            <ul>
            {% for consumption in apartment.consumption_set.all %}
                <li>{{ consumption.reading_date }}: {{ consumption.reading_value }}</li>
            {% endfor %}
            </ul>
        {% endfor %}
        </ul>
    {% else %}
        <p>No apartment data available.</p>
    {% endif %}
{% endblock %}

housingbook/templates/housingbook/privacy.html
{% extends 'housingbook/base.html' %}
{% block title %}Apartment {{ apartment.code }}{% endblock %}

{% block content %}
    Jó napot! Our privacy statement will go here.
{% endblock %}

housingbook/templates/housingbook/signup.html
{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
      {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="display: none">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
      {% endfor %}    <button type="submit">Sign up</button>
  </form>
{% endblock %}